server:
  port: 8888
spring:
  profiles:
    active: native, dev
  cloud:
    config:
      server:
        native:
          searchLocations: classpath:/configs/{profile}
management:
  security:
    enabled: true