server:
  port: 8888
spring:
  #profiles:
  #  active: dev
  cloud:
    config:
      server:
        git:
          uri: https://github.com/YKiselev/spring-cloud-poc.git
          searchPaths: configs/src/main/resources/{profile}
          cloneOnStart: true
          force-pull: true
          deleteUntrackedBranches: true
        #native:
        #  searchLocations: classpath:/configs/{profile}
security:
  user:
    password: '{cipher}AQAIwQ7vq3bfAG95mv+U45klkYXPVhOjiAeUELcMV584vIXm5P6e1JWanr3TWyb1r/iHG6wguajSur7n1W7aRkzeRvtn0GeFWt23gZI1qbg1DDH31WkhHFmw2Bk/eqobKKNg/ggZHLH9F/jYrNiRudF5l6Z66fSWaj+Ny9nf0zP8PFwkUasYlMiiTShgvvW5VaMn3q7BaFopMAls0Uti9LHiR23LzazJke7xyn5Ugp/WPtcSyv7YnbdWRs/5MKSYUSWKasech8UTZapfay8vzfb7VULAWZPTAZCgZu1RgDnuWblcRvOoL+buzIJDVwUGzXjhluiGJM36zO0zi6+7VLJsT1bVMx80Lchc+SkKkt397pRh5PLsyzcqzjNnbiCuNMI='
management:
  security:
    enabled: true